import 'package:flutter/material.dart';
import 'package:flutter_app_watherguru/utilities/constants.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WeatherForecastListWeather extends ChangeNotifier {
  WeatherForecastListWeather({
    this.id,
    this.main,
    this.description,
    this.icon,
  });

  WeatherForecastListWeather.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    main = json['main']?.toString();
    description = json['description']?.toString();
    icon = json['icon']?.toString();
  }

  String? description;
  String? icon;
  int? id;
  String? main;

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['main'] = main;
    data['description'] = description;
    data['icon'] = icon;
    return data;
  }

/*
{
  "id": 501,
  "main": "Rain",
  "description": "moderate rain",
  "icon": "10d"
} 
*/
}

class WeatherForecastListFeelsLike extends ChangeNotifier {
  WeatherForecastListFeelsLike({
    this.day,
    this.night,
    this.eve,
    this.morn,
  });

  WeatherForecastListFeelsLike.fromJson(Map<String, dynamic> json) {
    day = json['day']?.toDouble();
    night = json['night']?.toDouble();
    eve = json['eve']?.toDouble();
    morn = json['morn']?.toDouble();
  }

  double? day;
  double? eve;
  double? morn;
  double? night;

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['day'] = day;
    data['night'] = night;
    data['eve'] = eve;
    data['morn'] = morn;
    return data;
  }

/*
{
  "day": 279.75,
  "night": 280.63,
  "eve": 280.06,
  "morn": 278.09
} 
*/
}

class WeatherForecastListTemp extends ChangeNotifier {
  WeatherForecastListTemp({
    this.day,
    this.min,
    this.max,
    this.night,
    this.eve,
    this.morn,
  });

  WeatherForecastListTemp.fromJson(Map<String, dynamic> json) {
    day = json['day']?.toDouble();
    min = json['min']?.toDouble();
    max = json['max']?.toDouble();
    night = json['night']?.toDouble();
    eve = json['eve']?.toDouble();
    morn = json['morn']?.toDouble();
  }

  double? day;
  double? eve;
  double? max;
  double? min;
  double? morn;
  double? night;

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['day'] = day;
    data['min'] = min;
    data['max'] = max;
    data['night'] = night;
    data['eve'] = eve;
    data['morn'] = morn;
    return data;
  }

/*
{
  "day": 281.87,
  "min": 278.91,
  "max": 282.91,
  "night": 282.91,
  "eve": 282.01,
  "morn": 279.81
} 
*/
}

class WeatherForecastList extends ChangeNotifier {
  WeatherForecastList({
    this.dt,
    this.sunrise,
    this.sunset,
    this.temp,
    this.feelsLike,
    this.pressure,
    this.humidity,
    this.weather,
    this.speed,
    this.deg,
    this.gust,
    this.clouds,
    this.pop,
    this.rain,
  });

  WeatherForecastList.fromJson(Map<String, dynamic> json) {
    dt = json['dt']?.toInt();
    sunrise = json['sunrise']?.toInt();
    sunset = json['sunset']?.toInt();
    temp = (json['temp'] != null)
        ? WeatherForecastListTemp.fromJson(json['temp'])
        : null;
    feelsLike = (json['feels_like'] != null)
        ? WeatherForecastListFeelsLike.fromJson(json['feels_like'])
        : null;
    pressure = json['pressure']?.toInt();
    humidity = json['humidity']?.toInt();
    if (json['weather'] != null) {
      final v = json['weather'];
      final arr0 = <WeatherForecastListWeather>[];
      v.forEach((v) {
        arr0.add(WeatherForecastListWeather.fromJson(v));
      });
      weather = arr0;
    }
    speed = json['speed']?.toDouble();
    deg = json['deg']?.toInt();
    gust = json['gust']?.toDouble();
    clouds = json['clouds']?.toInt();
    pop = json['pop']?.toInt();
    rain = json['rain']?.toDouble();
  }

  int? clouds;
  int? deg;
  int? dt;
  WeatherForecastListFeelsLike? feelsLike;
  double? gust;
  int? humidity;
  int? pop;
  int? pressure;
  double? rain;
  double? speed;
  int? sunrise;
  int? sunset;
  WeatherForecastListTemp? temp;
  List<WeatherForecastListWeather?>? weather;

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['dt'] = dt;
    data['sunrise'] = sunrise;
    data['sunset'] = sunset;
    if (temp != null) {
      data['temp'] = temp!.toJson();
    }
    if (feelsLike != null) {
      data['feels_like'] = feelsLike!.toJson();
    }
    data['pressure'] = pressure;
    data['humidity'] = humidity;
    if (weather != null) {
      final v = weather;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['weather'] = arr0;
    }
    data['speed'] = speed;
    data['deg'] = deg;
    data['gust'] = gust;
    data['clouds'] = clouds;
    data['pop'] = pop;
    data['rain'] = rain;
    return data;
  }

  String get iconUrl {
    return Constants.WEATHER_IMAGES_URL + (weather?[0]?.icon ?? '') + '.png';
  }

/*
{
  "dt": 1640606400,
  "sunrise": 1640592357,
  "sunset": 1640620622,
  "temp": {
    "day": 281.87,
    "min": 278.91,
    "max": 282.91,
    "night": 282.91,
    "eve": 282.01,
    "morn": 279.81
  },
  "feels_like": {
    "day": 279.75,
    "night": 280.63,
    "eve": 280.06,
    "morn": 278.09
  },
  "pressure": 993,
  "humidity": 96,
  "weather": [
    {
      "id": 501,
      "main": "Rain",
      "description": "moderate rain",
      "icon": "10d"
    }
  ],
  "speed": 5.17,
  "deg": 180,
  "gust": 12.56,
  "clouds": 85,
  "pop": 1,
  "rain": 6.34
} 
*/
}

class CityCoord extends ChangeNotifier {
  CityCoord({
    this.lon,
    this.lat,
  });

  CityCoord.fromJson(Map<String, dynamic> json) {
    lon = json['lon']?.toDouble();
    lat = json['lat']?.toDouble();
  }

  double? lat;
  double? lon;

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lon'] = lon;
    data['lat'] = lat;
    return data;
  }

/*
{
  "lon": -0.1257,
  "lat": 51.5085
} 
*/
}

class City {
  City({
    this.id,
    this.name,
    this.coord,
    this.country,
    this.population,
    this.timezone,
  });

  City.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    coord = (json['coord'] != null) ? CityCoord.fromJson(json['coord']) : null;
    country = json['country']?.toString();
    population = json['population']?.toInt();
    timezone = json['timezone']?.toInt();
  }

  CityCoord? coord;
  String? country;
  int? id;
  String? name;
  int? population;
  int? timezone;

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    if (coord != null) {
      data['coord'] = coord!.toJson();
    }
    data['country'] = country;
    data['population'] = population;
    data['timezone'] = timezone;
    return data;
  }

/*
{
  "id": 2643743,
  "name": "London",
  "coord": {
    "lon": -0.1257,
    "lat": 51.5085
  },
  "country": "GB",
  "population": 1000000,
  "timezone": 0
} 
*/
}

class WeatherForecast extends ChangeNotifier {
  WeatherForecast({
    this.city,
    this.cod,
    this.message,
    this.cnt,
    this.list,
  });

  WeatherForecast.fromJson(Map<String, dynamic> json) {
    city = (json['city'] != null) ? City.fromJson(json['city']) : null;
    cod = json['cod']?.toString();
    message = json['message']?.toDouble();
    cnt = json['cnt']?.toInt();
    if (json['list'] != null) {
      final v = json['list'];
      final arr0 = <WeatherForecastList>[];
      v.forEach((v) {
        arr0.add(WeatherForecastList.fromJson(v));
      });
      list = arr0;
    }
  }

  City? city;
  int? cnt;
  String? cod;
  List<WeatherForecastList?>? list;
  double? message;

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (city != null) {
      data['city'] = city!.toJson();
    }
    data['cod'] = cod;
    data['message'] = message;
    data['cnt'] = cnt;
    if (list != null) {
      final v = list;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['list'] = arr0;
    }
    return data;
  }

/*
{
  "city": {
    "id": 2643743,
    "name": "London",
    "coord": {
      "lon": -0.1257,
      "lat": 51.5085
    },
    "country": "GB",
    "population": 1000000,
    "timezone": 0
  },
  "cod": "200",
  "message": 4.1199003,
  "cnt": 7,
  "list": [
    {
      "dt": 1640606400,
      "sunrise": 1640592357,
      "sunset": 1640620622,
      "temp": {
        "day": 281.87,
        "min": 278.91,
        "max": 282.91,
        "night": 282.91,
        "eve": 282.01,
        "morn": 279.81
      },
      "feels_like": {
        "day": 279.75,
        "night": 280.63,
        "eve": 280.06,
        "morn": 278.09
      },
      "pressure": 993,
      "humidity": 96,
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "speed": 5.17,
      "deg": 180,
      "gust": 12.56,
      "clouds": 85,
      "pop": 1,
      "rain": 6.34
    }
  ]
} 
*/
}
